### PR TITLE
Fix IAM load from bucket

### PR DESCRIPTION
**Pull request by phuonghuynh**
For #26

### CODE REVIEW

**Comment by ronaldtse** [comment]
@erikbor could you help check? Thanks!

**Comment by phuonghuynh** [comment]
Sample usage: 
```
module "dynamic-iam-group" {
  source         = "../../"
  name           = "example-dynamic-iam-groups"
  bucket_name    = "example-dynamic-iam-groups-bucket"
  description    = "example usage of terraform-aws-authenticating-iam"
  time_to_expire = 300
  log_level = "DEBUG"

  iam_groups = [
    "test1.json", "test2.json"
  ]
}
```

File "test1.json"
```json
["phuonghqh1", "phuonghqh2"]
```

File "test2.json"
```json
["phuonghqh1"]
```

**Comment by erikbor** [comment]
@phuonghuynh,

Where can I define `"group_name": "${aws_iam_group.dyn_iam_access.name}"`?

Cheers

**Comment by ronaldtse** [comment]
@erikbor I believe `group_name` is inferred from the filenames of `iam_groups = [    "test1.json", "test2.json"  ]`.

**Comment by phuonghuynh** [comment]
Exactly @ronaldtse

**Comment by ronaldtse** [comment]
@phuonghuynh in any case could you help reverse the behavior, where we define the groups and files like this:

```
module "dynamic-iam-group" {
  source         = "../../"
  name           = "example-dynamic-iam-groups"
  bucket_name    = "example-dynamic-iam-groups-bucket"
  description    = "example usage of terraform-aws-authenticating-iam"
  time_to_expire = 300
  log_level = "DEBUG"

  iam_groups = [
    "${aws_iam_group.developers.name}"
  ]
}

resource "aws_iam_group" "developers" {
  name = "developers"
  path = "/users/"
}

resource "aws_s3_bucket_object" "object" {
  bucket = "example-dynamic-iam-groups-bucket"
  key    = "${aws_iam_group.developers.name}.json"
  content = <<EOF
["phuonghqh1", "phuonghqh2"]
EOF
}

```

**Comment by ronaldtse** [comment]
Or even this: (this allows fetching the bucket and filenames from the module)

```
module "dynamic-iam-group" {
  source         = "../../"
  name           = "example-dynamic-iam-groups"
  bucket_name    = "example-dynamic-iam-groups-bucket"
  description    = "example usage of terraform-aws-authenticating-iam"
  time_to_expire = 300
  log_level = "DEBUG"

  iam_groups = [
    "${aws_iam_group.developers.name}"
  ]
}

resource "aws_iam_group" "developers" {
  name = "developers"
  path = "/users/"
}

resource "aws_s3_bucket_object" "object" {
  bucket = "${module.dynamic-iam-group.bucket_name}"
  key    = "${module.dynamic-iam-group.iam_groups_json[0]}"
  content = <<EOF
["phuonghqh1", "phuonghqh2"]
EOF
}
```

**Comment by phuonghuynh** [comment]
@ronaldtse so the module dont need to maintain bucket objects itself? In that case, the module only need bucket name, no need to pass Objects' Keys to it.

So the new usage should be:
```
module "dynamic-iam-group" {
  source         = "../../"
  name           = "example-dynamic-iam-groups"
  bucket_name    = "example-dynamic-iam-groups-bucket"
  description    = "example usage of terraform-aws-authenticating-iam"
  time_to_expire = 300
  log_level = "DEBUG"
}
```

**Comment by ronaldtse** [comment]
That's true. Thanks @phuonghuynh !

**Comment by erikbor** [comment]
@phuonghuynh 

Your changes work! The API endpoint and Lambda function are working perfect.

Thank you.

Can you also update the README and examples please?

The code @ronaldtse provided for the s3 object works also very well:

```
resource "aws_s3_bucket_object" "object" {
  bucket = "${aws_s3_bucket.dyn-iam-access.id}"
  key = "${aws_iam_group.dyn_iam_access.name}"
  content = <<EOF
["test1", "test2"]
EOF
```

Just need to be careful that there's no `.json` extension in the filename.

**Comment by ronaldtse** [comment]
@phuonghuynh are we supposed to have or not have the `.json` extension? It seems more reasonable to have the extension explicitly provided. Thanks.

**Comment by phuonghuynh** [comment]
I think we need to require ".json" to mention the file content should be in JSON format. But the code now can read them all. ^

**Pull request merged**
