### PR TITLE
Fix Event is none in authorize function

### PR DESCRIPTION
**Pull request by phuonghuynh**
Attach Event object to the handle function which causes #12

### CODE REVIEW

**Comment by erikbor** [comment]
Will try now

**Comment by erikbor** [comment]
Hi @phuonghuynh,

I just tried the update but I still have the problem where `user1` authenticates but `user2` is added to the dynamic security group.

**Comment by phuonghuynh** [comment]
@erikbor Could you help to check `event` is `None` or not in Lambda CloudWatch Log ? as screenshot bellow

screenshot_2

**Comment by erikbor** [comment]
`event` is not in any of the CloudWatch logs

**Comment by phuonghuynh** [comment]
@erikbor Could you check Lambda Function `authorize-*` has following code as bellow?


screenshot_1

And file `args.py` should has Log Level set to `DEBUG` (by module "dyn-iam-access")

screenshot_3

**Comment by erikbor** [comment]
@phuonghuynh I just completely deleted all the dyn iam resources and ran terraform apply again and now the correct user is put the dynamic security group!

**Comment by phuonghuynh** [comment]
Nice but its weird ^

**Comment by phuonghuynh** [comment]
@erikbor its good to make a new release for this function ?

**Comment by erikbor** [comment]
Let me test it some more with more user accounts, I'll get back to you in a hour.

**Comment by erikbor** [comment]
@phuonghuynh it's all good and works flawless! thanks for the fixes

**Pull request merged**
